// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IDL
{
    internal sealed partial class Vsix
    {
        public const string Id = "IDL.9b84ff34-a900-4d2b-ac64-ae1d845ae122";
        public const string Name = "IDL";
        public const string Description = @"Basic language support for IDL, MIDL and WebIDL. Provides syntax highlighting, outlining, commenting and more...";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
